env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/vue3-recommended'
  - 'eslint:recommended'
  - '@vue/typescript/recommended'
parserOptions:
  ecmaVersion: 12
plugins:
  - vue
  - '@typescript-eslint'
rules:
  {
    'indent': ['error', 2],
    'vue/max-attributes-per-line':
      ['error', { 'singleline': { 'max': 3 }, 'multiline': { 'max': 1 } }],
    'semi': ['error', 'never'],
    'no-unreachable': 'error',
  }
globals:
  {
    'defineProps': 'readonly',
    'defineEmits': 'readonly',
    'defineExpose': 'readonly',
    'withDefaults': 'readonly',
  }
